server:
  port: 8081
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: false
graphiql:
    mapping: /graphiql
    endpoint: /graphql
    enabled: true
    pageTitle: GraphiQL